version: "3.2"
services:
    train_object_detection:
        build: .
        volumes:
            - ${PWD}:/tf/
        working_dir: /tf
        command: bash -c "./scripts/train_object_detection.sh"
        devices:
            - /dev/nvidia0
        environment:
            NVIDIA_VISIBLE_DEVICES: 0
            EPOCHS: 70
            BATCH_SIZE: 8
            MODEL_TO_LOAD: None
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [ gpu ]

    predict_object_detection:
        build: .
        volumes:
            - ${PWD}:/tf/
        working_dir: /tf
        command: bash -c "./scripts/predict.sh"
        devices:
            - /dev/nvidia0
        environment:
            NVIDIA_VISIBLE_DEVICES: 0
            WEIGHTS_PATH: None
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [ gpu ]

    tensorboard:
        image: tensorflow/tensorflow:2.4.0
        ports:
            - 6006:6006
        volumes:
            - ${PWD}:/tf/
        command: bash -c "pip install -U tensorboard-plugin-profile; tensorboard --bind_all --logdir tf/experiments/"

